### ISSUE TITLE
chia plot status preventing files from updating in syncthing 

### ISSUE THREAD

**Issue by Waloumi** [grayfallstown/Chia-Plot-Status#40] opened 2021-05-13 20:46 UTC
apologies in advance if this is not relevant to chia plot status, if you still wanna know, read the following
using windows 10, ubuntu 18.04

so i've been trying to get logs created on an ubuntu machine to be monitored in chia plot status
to do that,  i tried using syncthing to make a shared folder from linux to windows to be able to have my windows chia plot status app to read the logs

what ensued is this: https://forum.syncthing.net/t/syncthing-cannot-sync-files-that-are-being-used/16803 (syncthing cannot update the log files coming from ubuntu into the syncthing folder because they are open in chia plot status)
according to the creator of syncthing, it seems like chia plot status is **holding exclusive access** to the file and so syncthing cannot update the logs.
What doesnt make sense to me is that chia plot status can read logs being written by powershell when a plot is running and writing the .txt files just fine.
I'll probably find another solution but for now it seems like a good one to monitor multiple plotting machines on one PC, if it worked.
Thank you

**Comment by grayfallstown** [comment] 2021-05-14 05:53
Chia Plot Status keeps the files open with non exclusive read access explicitly accepting shared access so that other processes can read or even write to the file.

Anyway, I just implemented an option to force Chia Plot Status to close the files once read, forcing it to re-read the entire logfile every time it wants to update the data shown.
This will cause more IO and CPU usage, but should work with Syncthing.

This is how to set this up:

- Install version 0.9.9 which I will release shortly
- Start and then close Chia Plot Status (this adds the new config option to the config file)
- Go into your home dir (`/home/<username>` on linux, `C:\Users\<username>` on windows)
- Open the file `ChiaPlotStatu.config.json` you will find there
- Search for the Option `AlwaysDoFullRead` and change it from `false` to `true`
- Save and start Chia Plot Status

**Comment by Waloumi** [comment] 2021-05-14 08:15
That's awesome, thank you for trying to help! I tried the update and the .json file change but this is what i see when i add my plots
![image](https://user-images.githubusercontent.com/36631015/118242167-5262bd80-b49d-11eb-8522-c697de5e3af0.png)

**Comment by grayfallstown** [comment] 2021-05-14 08:56
A mistake of mine prevented both the reading and the closing of files, please try one more time: https://github.com/grayfallstown/Chia-Plot-Status/releases/download/0.9.9/Setup.exe

**Comment by Waloumi** [comment] 2021-05-14 09:56
Works now, syncthing is finding no issue to sync. Great work! Thank you!

**Closed** 2021-05-14 09:57 UTC

**Comment by VONHALLE** [comment] 2021-05-15 06:28
I try using onedrive to sync local logs from various plotters but run into same issue - local log file can not be synced because locked (in use by another app). Plot Status is not even running on the other end so this must be a local issue - creating the plots via CLI and use startprocess with -redirectoutput. 

Any idea/workaround? Thanks!

**Comment by grayfallstown** [comment] 2021-05-15 06:32
Did you try the fix above?

**Comment by VONHALLE** [comment] 2021-05-15 06:44
I updated Plot Status, yes, but this seems to be a local issue on the plotter rig - the log file does not even get uploaded by onedrive, showing a sync problem stating the log file is in use - which can only mean by the CLI. I searched but found no way to force onedrive to upload nevertheless.

**Comment by grayfallstown** [comment] 2021-05-15 08:07
I would ditch onedrive then

**Comment by VONHALLE** [comment] 2021-05-15 08:13
syncthing under win10 confirmed to not have that behaviour? WIll try then.

**Comment by VONHALLE** [comment] 2021-05-15 08:22
syncthing = same problem. now looking to write script that actual copies the file every x seconds to a file that can then be synced... already feeling like a sysadmin :)

**Comment by grayfallstown** [comment] 2021-05-15 08:24
syncthing is confirmed working when you apply the fix above. Did you change the setting?

**Comment by VONHALLE** [comment] 2021-05-15 08:28
Sorry, I don't get something obv. What kind of fix could YOU provide for that problem? You could modify your program so it does not lock the log file while/after accessing it but the problem I have is purly on the plotter pc. CLI starts a process that creates log file by -redirectoutput but locks that file while writing to it, so onedrive and other sync solutions can only access it after CLI started process is done.

**Comment by grayfallstown** [comment] 2021-05-15 08:32
You can open the log files in notepad which means a sync software could sync it. The sync software just needs to accept shared access. Chia Plot Status does the same thing.

**Comment by grayfallstown** [comment] 2021-05-16 08:07
Cleaned up some support comments
