### ISSUE TITLE
Suggestion: Web UI!

### ISSUE THREAD

**Issue by timonoj** [grayfallstown/Chia-Plot-Status#62] opened 2021-05-21 01:59 UTC
Hi! I think a common scenario among many people is having the Chia farmer running in a headless machine, so it saves on resources. Then you point the GUI from a second machine to the server to check on the status. This use case scenario blocks this app from being used. As it clearly would need to be installed locally to have access to the local log files under .chia/mainnet/plotter, but then the UI can't be launched without a desktop. 

The easiest alternative would be to just throw a web UI URL:PORT where you could just check from anywhere within the network, regardless a desktop environment being installed on the server or not. 

Thanks!

**Comment by grayfallstown** [comment] 2021-05-21 06:06
> This use case scenario blocks this app from being used.

No. You would simply install Chia Plot Status on your desktop and either

- mount the log directory of your headless machines on your desktop as network share
- sync the log files from your headless machines to your desktop via cloud sync apps
- write a simple cron job to sync the log directory via scp, rsync or something similar

and add the folders with the logs of your headless machines in Chia Plot Status.

And this is a duplicate of #59.

**Closed** 2021-05-21 18:35 UTC
Labels: duplicate
