### ISSUE TITLE
Virus Thread

### ISSUE THREAD

**Issue by gringomxstar** [grayfallstown/Chia-Plot-Status#48] opened 2021-05-17 15:23 UTC
Hi,
Great Work thank you!
Is this normal?
The following Virus Warning shows up as follows:
C:\Program Files (x86)\ChiaPlotStatus\ChiaPlotStatus\Avalonia.Win32.dll 
Trojan:Win32/Emali.A!cl

**Comment by grayfallstown** [comment] 2021-05-17 15:29
Thanks for the report.
Duplicate of #47, so closing this for now.

**Closed by grayfallstown** 2021-05-17 15:29 UTC
